language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t josel1204/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true josel1204/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "Dockerfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-532984612430"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY