language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t josel1204/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true josel1204/frontend npm run test -- --coverage
